### ISSUE TITLE
How to use this wrapper

### ISSUE THREAD

**Issue by brianmituka** [orbinson/opentelemetry-osgi-wrappers#4]
Hello, thank you for the work you have done with this library. I am not very clear on where to start if I wanted to make use of this library. I came across it from this site https://adapt.to/2024/schedule/observability-in-aemaacs-with-opentelemetry and I would like to understand how it works. Thank You

**Comment by royteeuwen** [comment]
hey @brianmituka . You can watch the recording and look at the demo referenced in the presentation: https://github.com/orbinson/adaptto-opentelemetry-demo

Do you want to use this in AEM as a Cloud service, or do you have another application? If you want to use it in AEMaaCS, check out the following repo as well: 
https://github.com/orbinson/aemaacs-opentelemetry-instrumentation
